name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # 12시간마다 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: 9bfish8        # 여기에 본인의 GitHub 사용자명을 입력
          gif_out_path: dist/github-contribution-grid-snake.svg
          svg_out_path: dist/github-contribution-grid-snake-dark.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
